[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
example = "feat: this feature enable customize through config file"
schema = "<type>(<scope>): <body>"
schema_pattern = "(?s)(build|chore|ci|docs|feat|fix|perf|refactor|revert|release|style|test|ui|workflow|wip)(\\(\\S+\\))?:( [^\n\r]+)((\n\n.*)|(\\s*))?$"
bump_pattern = "^(break|new|fix|hotfix)"
bump_map = {"break" = "MAJOR", "new" = "MINOR", "fix" = "PATCH", "hotfix" = "PATCH"}
change_type_order = ["build", "chore", "ci", "feat", "fix", "perf","refactor", "revert", "release", "style", "test", "workflow", "wip"]
commit_parser = "(?s)(build|chore|ci|docs|feat|fix|perf|refactor|revert|release|style|test|workflow|wip)(\\(\\S+\\))?:( [^\n\r]+)((\n\n.*)|(\\s*))?$"
[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [{value = "feat", name = "feat: A new feature."}, {value = "fix", name = "fix: A bug fix."}]
# choices = ["feature", "fix"]  # short version
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Body."

[[tool.commitizen.customize.questions]]
type = "confirm"
name = "show_message"
message = "Do you want to add body message in commit?"
